creation_rules:
  - age: >-
      age13r4554wpmkkmh6lk2ky9d68nj7ctfgqv9d4f4ndu66h9usnxjfwsdcqvr7,
      age1asf5cdz4y8j87x47upgqj7fgxeelvycqvylhdvn294vspc9qqedsg4h3ut,
      age1nf788rkct8jls9fgajam6tufyf5wm00s7tx824yzdjmdm532zdzquxn5sp,
      age1lkymrw5sua4me8etf8dtlu6gclssfcyq3yehgxh6za54t69r2ytq0u0dp0
